version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: company-mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: CompanyDB2025!
      MYSQL_DATABASE: company_db
    ports:
      - "3306:3306"

  django:
    build:
      context: .
      dockerfile: ./company/Dockerfile
    container_name: company-django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: company-frontend
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  mysql_data: