# Generated by Django 5.2.4 on 2025-07-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_performancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdata',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_files/'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='policy_count',
            field=models.CharField(blank=True, choices=[('1-2', '1~2건'), ('3-4', '3~4건'), ('5-6', '5~6건'), ('7-8', '7~8건'), ('9-10', '9~10건'), ('10+', '10건 이상')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='premium_range',
            field=models.CharField(blank=True, choices=[('UNKNOWN', '모름'), ('5-10', '5만~10만'), ('10-20', '10만~20만'), ('20-30', '20만~30만'), ('30-50', '30만~50만'), ('50-100', '50만~100만'), ('100+', '100만 이상')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='status',
            field=models.CharField(choices=[('PENDING', '작업전'), ('ABSENT', '부재'), ('FAIL', '실패'), ('SUCCESS_1', '1차성공'), ('SUCCESS_2', '2차성공'), ('PROMISING', '가망')], default='PENDING', max_length=20),
        ),
    ]
