# Generated by Django 5.2.4 on 2025-07-15 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clientdata_audio_file_clientdata_policy_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdata',
            name='employee_note',
            field=models.TextField(blank=True, null=True, verbose_name='직원 메모 (시간, 장소)'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_files/', verbose_name='녹취 파일'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='contact',
            field=models.CharField(max_length=100, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='name',
            field=models.CharField(max_length=100, verbose_name='고객명'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='note',
            field=models.TextField(blank=True, verbose_name='관리자 메모 (특이사항)'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='담당 직원'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='policy_count',
            field=models.CharField(blank=True, choices=[('1-2', '1~2건'), ('3-4', '3~4건'), ('5-6', '5~6건'), ('7-8', '7~8건'), ('9-10', '9~10건'), ('10+', '10건 이상')], max_length=10, null=True, verbose_name='가입개수'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='premium_range',
            field=models.CharField(blank=True, choices=[('UNKNOWN', '모름'), ('5-10', '5만~10만'), ('10-20', '10만~20만'), ('20-30', '20만~30만'), ('30-50', '30만~50만'), ('50-100', '50만~100만'), ('100+', '100만 이상')], max_length=10, null=True, verbose_name='총금액대'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='registration_date',
            field=models.DateField(verbose_name='접수일'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='status',
            field=models.CharField(choices=[('PENDING', '작업전'), ('ABSENT', '부재'), ('FAIL', '실패'), ('SUCCESS_1', '1차성공'), ('SUCCESS_2', '2차성공'), ('PROMISING', '가망')], default='PENDING', max_length=20, verbose_name='현황'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='date',
            field=models.DateField(verbose_name='실적일'),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='직원'),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='record_type',
            field=models.CharField(max_length=100, verbose_name='실적 종류'),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='value',
            field=models.IntegerField(verbose_name='실적 값'),
        ),
    ]
