# Generated by Django 5.2.4 on 2025-07-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_clientdata_employee_note_alter_clientdata_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdata',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='clientdata',
            name='birth_date',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='생년월일(8자리)'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='detailed_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='상세주소(읍면동 이하)'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남'), ('F', '여')], max_length=1, null=True, verbose_name='성별'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='gugun',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='구/군'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='sido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='시/도'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='기본 주소'),
        ),
    ]
