# Generated by Django 5.2.4 on 2025-07-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_clientdata_registration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdata',
            name='audio_file_2',
            field=models.FileField(blank=True, null=True, upload_to='audio_files/', verbose_name='녹취 파일 2'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_files/', verbose_name='녹취 파일 1'),
        ),
    ]
