# Generated by Django 5.2.4 on 2025-07-16 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0008_incentive_siteconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('birth_date', models.CharField(blank=True, max_length=8, null=True, verbose_name='생년월일(8자리)')),
                ('gender', models.CharField(blank=True, choices=[('M', '남'), ('F', '여')], max_length=1, null=True, verbose_name='성별')),
            ],
        ),
    ]
