# Generated by Django 5.2.4 on 2025-07-16 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_employeeprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdata',
            name='distribution_date',
            field=models.DateField(blank=True, null=True, verbose_name='배분날짜'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='info_file',
            field=models.FileField(blank=True, null=True, upload_to='info_files/', verbose_name='정보파일'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='is_distributed',
            field=models.BooleanField(default=False, verbose_name='배분여부'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='transmission_status',
            field=models.CharField(choices=[('Y', '전송'), ('N', '미전송')], default='N', max_length=1, verbose_name='전송여부'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='담당 직원'),
        ),
    ]
