# Generated by Django 5.2.4 on 2025-07-18 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_employeeprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(auto_now_add=True, verbose_name='근무일')),
                ('check_in_time', models.DateTimeField(auto_now_add=True, verbose_name='출근 시간')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='퇴근 시간')),
                ('memo', models.CharField(blank=True, max_length=200, verbose_name='메모')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='직원')),
            ],
            options={
                'verbose_name': '출퇴근 기록',
                'verbose_name_plural': '출퇴근 기록',
                'ordering': ['-work_date', '-check_in_time'],
                'unique_together': {('employee', 'work_date')},
            },
        ),
    ]
