# Generated by Django 5.2.4 on 2025-07-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_attendancerecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incentive',
            options={'ordering': ['reward_amount'], 'verbose_name': '건수별 인센티브', 'verbose_name_plural': '건수별 인센티브'},
        ),
        migrations.AlterField(
            model_name='incentive',
            name='case_count',
            field=models.CharField(max_length=50, verbose_name='조건 (건수)'),
        ),
        migrations.AlterField(
            model_name='incentive',
            name='reward_amount',
            field=models.PositiveIntegerField(verbose_name='보상 (원)'),
        ),
    ]
